# Generated by Django 5.1.3 on 2024-11-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_size_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
